carav/urls.py
from django.conf.urls import url

from carav import views

urlpatterns = [
    url('^create_water_fountain$', views.create_water_fountain, name='create_water_fountain'),
    url('^all_water_fountains$', views.all_water_fountains, name='all_water_fountains'),
    url('^delete_water_fountain$', views.delete_water_fountain, name='delete_water_fountain'),
    url('^update_water_fountain$', views.update_water_fountain, name='update_water_fountain'),
]

homepage/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    url(r'^django-admin/', admin.site.urls),
    url(r'^wagtail-admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^', include(wagtail_urls)),
    url(r'^carav/', include('carav.urls', namespace='carav')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, StreamFieldPanel
from wagtail.core.blocks import StructBlock, RichTextBlock, URLBlock, \
    PageChooserBlock
from wagtail.core.fields import RichTextField, StreamField
from wagtail.core.models import Page, Orderable
from wagtail.search import index


# region Blocks
class HomePageCardBlock(StructBlock):
    page = PageChooserBlock(required=False)
    url = URLBlock(required=False)
    content = RichTextBlock()

    class Meta:
        template = 'blog/blocks/home_page_card_block.html'
        help_text = 'One of Page or Url is required'
# endregion


# region Pages
class BaseFormattedPage(Page):

    class Meta:
        abstract = True


class Home(BaseFormattedPage):
    content = StreamField([
        ('link_blocks', HomePageCardBlock()),
    ])

    content_panels = BaseFormattedPage.content_panels + [
        StreamFieldPanel('content'),
    ]


class BlogIndex(BaseFormattedPage):
    banner = models.ImageField(blank=True)

    # noinspection PyMethodOverriding
    def get_context(self, request):
        # Update context to include only published posts, ordered by reverse-chron
        context = super(BlogIndex, self).get_context(request)
        blog_pages = self.get_children().live().order_by('-first_published_at')
        context['blog_pages'] = blog_pages
        return context

    content_panels = BaseFormattedPage.content_panels + [
        FieldPanel('banner'),
    ]
    subpage_types = ['blog.Blog']


class Blog(BaseFormattedPage):
    date = models.DateField('Post date', default=timezone.now)
    banner = models.ImageField(blank=True)
    body = RichTextField(blank=False)

    search_fields = BaseFormattedPage.search_fields + [
        index.SearchField('body'),
    ]

    content_panels = BaseFormattedPage.content_panels + [
        MultiFieldPanel([
            FieldPanel('date'),
            FieldPanel('banner'),
        ], heading='Blog information'),
        FieldPanel('body', classname='full'),
    ]

    parent_page_types = ['blog.BlogIndex']
    subpage_types = []


class Map(BaseFormattedPage):
    template = 'carav/map.html'
    banner = models.ImageField(blank=True)

    content_panels = BaseFormattedPage.content_panels + [
        FieldPanel('banner'),
    ]

    parent_page_types = ['blog.Home']
    subpage_types = []
# endregion

carav/models.py
from django.db import models
from django.utils import timezone


class WaterFountain(models.Model):
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(default=timezone.now)
    lat = models.FloatField('Latitude')
    lng = models.FloatField('Longitude')
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return 'WaterFountain #{} @{},{}'.format(self.id, self.lat, self.lng)

carav/forms.py
from django import forms

from carav import models


class WaterFountainForm(forms.ModelForm):
    class Meta:
        model = models.WaterFountain
        exclude = ['created', 'updated']

blog/views.py
from django.shortcuts import render

# Create your views here.

carav/views.py
import logging
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.decorators.http import require_POST, require_GET

from carav import models

logger = logging.getLogger(__name__)


@require_POST
def create_water_fountain(request):
    """
    Creates a water fountain object in the db with given lat/lng.

    :param request: HTTP POST request, contains 'lat' and 'lng' required params which contain floating-point numbers
    :return: HTTP 200/OK JSON response
    """
    if 'lat' not in request.POST:
        logger.error('lat not in request')
        return HttpResponseBadRequest('lat is required')
    if 'lng' not in request.POST:
        logger.error('lng not in request')
        return HttpResponseBadRequest('lng is required')
    lat = request.POST['lat']
    lng = request.POST['lng']
    if models.WaterFountain.objects.filter(lat=lat, lng=lng).exists():
        logger.error('Duplicate latitude and longitude')
        return HttpResponseBadRequest('duplicate latitude and longitude')
    water_fountain = models.WaterFountain.objects.create(lat=lat, lng=lng)
    logger.info('Created a new water fountain: {}'.format(water_fountain))
    return JsonResponse({'id': water_fountain.id})


@require_GET
def all_water_fountains(request):
    """
    Retrieves a list of every water fountain in db.

    :param request: HTTP GET request
    :return: HTTP 200/OK JSON response, contains 'data' object: a list where each element is object with following keys:
    `lat`, `lng`, `id`
    """
    all_fountains = models.WaterFountain.objects.filter(deleted=False)
    all_list = [{'lat': water_fountain.lat, 'lng': water_fountain.lng, 'id': water_fountain.id}
                for water_fountain in all_fountains]
    return JsonResponse({'data': all_list})


@require_POST
def delete_water_fountain(request):
    """
    Soft deletes the water fountain with given id.

    :param request: HTTP DELETE request, contains single param: id
    :return: HTTP SUCCESS response
    """
    if 'id' not in request.POST:
        logger.error('id not in request')
        return HttpResponseBadRequest('id is required')
    water_fountain_id = request.POST['id']
    if not models.WaterFountain.objects.filter(id=water_fountain_id).exists():
        logger.error('water fountain does not exist')
        return HttpResponseBadRequest('water fountain with id {} does not exist'.format(water_fountain_id))
    water_fountain = models.WaterFountain.objects.get(id=water_fountain_id)
    if water_fountain.deleted:
        logger.error('water fountain already deleted')
        return HttpResponseBadRequest('already deleted')
    water_fountain.deleted = True
    water_fountain.save()
    logger.info('Deleted water fountain with id {}: {}'.format(water_fountain_id, water_fountain))
    return JsonResponse({})


@require_POST
def update_water_fountain(request):
    """
    Updates the marker with given id to new coordinates

    :param request: HTTP POST request, contains `id`, `lat`, `lng`
    :return: HTTP SUCCESS response
    """
    if 'id' not in request.POST:
        logger.error('no id in request')
        return HttpResponseBadRequest('id is required')
    if 'lat' not in request.POST:
        logger.error('no lat in request')
        return HttpResponseBadRequest('lat is required')
    if 'lng' not in request.POST:
        logger.error('no lng in request')
        return HttpResponseBadRequest('lng is required')
    water_fountain_id = request.POST['id']
    if not models.WaterFountain.objects.filter(id=water_fountain_id).exists():
        logger.error('water fountain does not exist with given id: {}'.format(water_fountain_id))
        return HttpResponseBadRequest('water fountain with id {} does not exist'.format(water_fountain_id))
    water_fountain = models.WaterFountain.objects.get(id=water_fountain_id)
    water_fountain.lat = request.POST['lat']
    water_fountain.lng = request.POST['lng']
    water_fountain.save()
    logger.info('Updated water fountain: {}'.format(water_fountain))
    return JsonResponse({})

blog/templates/blog/base_formatted.html
{% extends "blog/base_html.html" %}

{% load static %}

{% block html_body %}

    {% spaceless %}

        <div class="content">

            <div class="uk-background-cover uk-flex background-grey min-height-header-footer"
                 {% if page.banner %}style="background-image: url({{ page.banner.url }});"{% endif %}>
                <div class="uk-width-auto uk-text-center uk-margin-auto uk-margin-auto-vertical">
                    <h1 class="uk-heading-primary uk-text-uppercase uk-width-auto uk-text-center uk-margin-auto uk-margin-auto-vertical inverse-text-color-background">
                        {% block title %}{% endblock title %}
                    </h1>
                </div>
            </div>

            <div class="uk-container uk-container-small uk-margin-large">
                <div class="uk-grid-match uk-flex-column" data-uk-grid>
                    <div>
                        {% block content %}{% endblock content %}
                    </div>
                </div>
            </div>

        </div>

        {% include "blog/components/footer.html" %}

    {% endspaceless %}

{% endblock html_body %}

blog/templates/blog/base_html.html
{% spaceless %}
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>{% block title %}Lazy Developer{% endblock title %} - Lazy Developer</title>

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="google-site-verification" content="DowrQPC0oO2d6GAu2joIhqFk_IKLA2SGG1MrbJIlRss">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.11/css/uikit.min.css"/>
        <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans">
        <link rel="icon" type="image/png" href="{% static 'favicon-32x32.png' %}" sizes="32x32"/>
        <link rel="icon" type="image/png" href="{% static 'favicon-16x16.png' %}" sizes="16x16"/>

        {% block head %}{% endblock head %}
    </head>
    <body>
    {% block html_body %}{% endblock html_body %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.11/js/uikit.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.11/js/uikit-icons.min.js"></script>
    </body>
    </html>
{% endspaceless %}

blog/templates/blog/blocks/description_list_block.html
{% load wagtailcore_tags %}

{% spaceless %}
    <dl class="uk-description-list">
        {% for pair in value.content %}
            {% include_block pair %}
        {% endfor %}
    </dl>
{% endspaceless %}

blog/templates/blog/blocks/description_list_item_block.html
{% load wagtailcore_tags %}

{% spaceless %}
    <dt>{{ value.data_title }}</dt>
    <dd>{{ value.data_definition }}</dd>
{% endspaceless %}

blog/templates/blog/blocks/download_button_block.html
{% load wagtailcore_tags %}

{% spaceless %}
    <a href="{{ value.url }}" class="uk-button uk-button-primary uk-button-large" download>{{ value.text }}</a>
{% endspaceless %}

blog/templates/blog/blocks/h3_with_id_block.html
{% load wagtailcore_tags %}

{% spaceless %}
    <h3{% if self.id|length > 0 %} id="{{ self.id }}"{% endif %}>{{ self.title }}</h3>
    {{ self.content }}
{% endspaceless %}

blog/templates/blog/blocks/h4_with_id_block.html
{% load wagtailcore_tags %}

{% spaceless %}
    <h4{% if self.id|length > 0 %} id="{{ self.id }}"{% endif %}>{{ self.title }}</h4>
    {{ self.content }}
{% endspaceless %}

blog/templates/blog/blocks/home_page_card_block.html
<div>
    <a href="{% if self.page %}{{ self.page.url }}{% else %}{{ self.url }}{% endif %}" class="uk-link-reset">
        <div class="uk-card uk-card-primary uk-card-hover uk-card-body uk-light">
            {{ self.content }}
        </div>
    </a>
</div>

blog/templates/blog/blocks/portfolio_card_block.html
{% load wagtailcore_tags %}
{% load wagtailimages_tags %}

{% spaceless %}
    <div class="uk-card uk-card-default uk-card-hover"{% if self.id|length > 0 %} id="{{ self.id }}"{% endif %}>
        <a href="{{ self.link }}">
            <div class="uk-card-media-top">
                {% image self.image height-160 class="uk-align-center" %}
            </div>
        </a>
        <div class="uk-card-body">
            <h3 class="uk-card-title"><a href="{{ self.link }}">{{ self.title }}</a></h3>
            {{ self.content }}
        </div>
    </div>
{% endspaceless %}

blog/templates/blog/blocks/section_block.html
{% load wagtailcore_tags %}

{% spaceless %}
    <div class="uk-section-small" {% if self.id|length > 0 %} id="{{ self.id }}"{% endif %}>
        <div class="uk-container">
            <h2>{{ self.title }}</h2>
            {{ self.content }}
        </div>
    </div>
{% endspaceless %}

blog/templates/blog/blocks/small_grid_block.html
{% load wagtailcore_tags %}

{% spaceless %}
    <div class="uk-child-width-{{ self.dividend }}-{{ self.divisor }}@m uk-grid-small uk-grid-match" data-uk-grid>
        {{ self.content }}
    </div>
{% endspaceless %}

blog/templates/blog/blog.html
{% extends "blog/base_formatted.html" %}

{% load wagtailcore_tags wagtailimages_tags %}
{% load disqus_tags %}

{% spaceless %}

    {% block title %}{{ page.title }}{% endblock title %}
    {% block content %}
        <p class="uk-text-meta">{{ page.date }}</p>

        {{ page.body|richtext }}

        <p><a href="{{ page.get_parent.url }}">Return to blog</a></p>

        {% disqus_show_comments %}

    {% endblock %}

{% endspaceless %}

blog/templates/blog/blog_index.html
{% extends "blog/base_formatted.html" %}

{% load wagtailcore_tags %}

{% spaceless %}

    {% block title %}{{ page.title }}{% endblock %}
    {% block content %}

        <div class="uk-section">
            <ul>
                {% for post in blog_pages %}
                    {% with post=post.specific %}
                        <li>
                            <a href="{% pageurl post %}">{{ post.title }}</a>
                            <span class="uk-align-right uk-margin-remove-bottom uk-text-meta uk-visible@l">{{ post.date }}</span>
                        </li>
                    {% endwith %}
                {% endfor %}
            </ul>
        </div>

    {% endblock %}

{% endspaceless %}

blog/templates/blog/blog_index_page.html
{% extends "base_formatted.html" %}

{% load wagtailcore_tags %}

{% spaceless %}

    {% block title %}{{ page.title }}{% endblock %}
    {% block content %}

        <div class="uk-section">
            <ul>
                {% for post in blog_pages %}
                    {% with post=post.specific %}
                        <li><a href="{% pageurl post %}">{{ post.title }}</a></li>
                    {% endwith %}
                {% endfor %}
            </ul>
        </div>

    {% endblock %}

{% endspaceless %}

blog/templates/blog/blog_page.html
{% extends "base_formatted.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% spaceless %}

    {% block title %}{{ page.title }}{% endblock title %}
    {% block content %}
        <p class="meta">{{ page.date }}</p>

        {% with categories=page.categories.all %}
            {% if categories %}
                <h3>Posted in:</h3>
                <ul>
                    {% for category in categories %}
                        <li style="display: inline">
                            {% image category.icon fill-32x32 style="vertical-align: middle" %}
                            {{ category.name }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        {% endwith %}

        <div class="intro">{{ page.intro }}</div>

        {{ page.body|richtext }}

        {% for item in page.gallery_images.all %}
            <div style="float: left; margin: 10px">
                {% image item.image fill-320x240 %}
                <p>{{ item.caption }}</p>
            </div>
        {% endfor %}

        <p><a href="{{ page.get_parent.url }}">Return to blog</a></p>

    {% endblock %}

{% endspaceless %}

blog/templates/blog/components/footer.html
<div class="uk-grid uk-flex-center uk-flex-middle uk-background-secondary min-height-header-footer">
    <ul class="uk-iconnav">
        <li><a href="https://linkedin.com/in/babkenvardanyan" data-uk-icon="icon: linkedin"></a></li>
        <li><a href="https://github.com/axper" data-uk-icon="icon: github"></a></li>
    </ul>
</div>

blog/templates/blog/home.html
{% extends "blog/base_formatted.html" %}

{% load wagtailcore_tags %}

{% spaceless %}

    {% block title %}{{ page.title }}{% endblock %}
    {% block content %}
        <div class="uk-child-width-1-2@s uk-grid-match uk-margin-bottom" data-uk-grid>
            {% for block in page.content %}
                {% include_block block %}
            {% endfor %}
        </div>
    {% endblock content %}

{% endspaceless %}

blog/templates/blog/home_page.html
{% extends "base_formatted.html" %}

{% load wagtailcore_tags %}

{% spaceless %}

    {% block title %}{{ page.title }}{% endblock %}
    {% block content %}
        <div class="uk-child-width-1-2@s uk-grid-match uk-margin-bottom" data-uk-grid>
            {% for block in page.content %}
                {% include_block block %}
            {% endfor %}
        </div>
    {% endblock content %}

{% endspaceless %}

carav/templates/carav/map.html
{% extends "blog/base_html.html" %}

{% load static %}
{% load disqus_tags %}

{% block title %}{{ page.title }}{% endblock %}

{% block html_body %}

    {% spaceless %}

        <div class="content">

            <div class="uk-background-cover uk-flex background-grey min-height-header-footer"
                 {% if page.banner %}style="background-image: url({{ page.banner.url }});"{% endif %}>
                <div class="uk-width-auto uk-text-center uk-margin-auto uk-margin-auto-vertical">
                    <h1 class="uk-heading-primary uk-text-uppercase uk-width-auto uk-text-center uk-margin-auto uk-margin-auto-vertical inverse-text-color-background">
                        {{ page.title }}
                    </h1>
                </div>
            </div>

            <div class="uk-container uk-container-large uk-margin-large">
                <div id="map" class="uk-margin-bottom yerevan-map"></div>
                <div hidden>
                    <div id="form">

                        <fieldset class="uk-fieldset">

                            <legend class="uk-legend">Water Fountain</legend>

                            <div class="uk-margin">
                                <input type="button" class="uk-button uk-button-primary uk-width-1-1"
                                       value="Save" onclick="createOrUpdateWaterFountain()"/>
                            </div>

                            <div class="uk-margin">
                                <input type="button" class="uk-button uk-button-danger uk-width-1-1"
                                       value="Delete" onclick="deleteWaterFountain()"/>
                            </div>

                        </fieldset>

                    </div>
                </div>

                {% disqus_show_comments %}
            </div>

        </div>

        {% include "blog/components/footer.html" %}

        <script>
            function initMap() {
                var yerevan_republic_square = {lat: 40.1774452, lng: 44.5129515};
                var map = new google.maps.Map(document.getElementById('map'), {
                    zoom: 14,
                    center: yerevan_republic_square
                });

                infowindow = new google.maps.InfoWindow({
                    content: document.getElementById('form')
                });

                google.maps.event.addListener(map, 'click', function (event) {
                    if (typeof marker !== 'undefined' && marker.id == null) {
                        marker.setMap(null);
                    }
                    marker = new google.maps.Marker({position: event.latLng, map: map, draggable: true});
                    addClickListener(marker);
                    infowindow.open(map, marker);
                    google.maps.event.addListener(infowindow, 'closeclick', function (event) {
                        console.log('info window closed');
                        if (marker.id == null) {
                            marker.setMap(null);
                        }
                    });
                });

                $.getJSON("{% url 'carav:all_water_fountains' %}", function (data) {
                    $.each(data['data'], function (key, val) {
                        marker = new google.maps.Marker({position: val, id: val.id, map: map, draggable: true});
                        addClickListener(marker);
                    });
                });
            }

            function addClickListener(marker_to_add_listener_to) {
                google.maps.event.addListener(marker_to_add_listener_to, 'click', (function (mrk) {
                    return function () {
                        marker = mrk;
                        infowindow.open(map, mrk);
                    }
                })(marker_to_add_listener_to));
            }

            function createOrUpdateWaterFountain() {
                lat = marker.getPosition().lat();
                lng = marker.getPosition().lng();
                if (marker.id) {
                    $.post("{% url "carav:update_water_fountain" %}",
                        {
                            lat: lat,
                            lng: lng,
                            id: marker.id,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        })
                        .done(function (data) {
                            UIkit.notification({message: 'Water fountain updated. Lat: ' + lat + ', Lng: ' + lng + '!'});
                            infowindow.close();
                        })
                        .fail(function () {
                            UIkit.notification({message: 'Failed updating water fountain.', status: 'danger'});
                        });
                } else {
                    $.post("{% url "carav:create_water_fountain" %}",
                        {
                            lat: lat,
                            lng: lng,
                            csrfmiddlewaretoken: '{{ csrf_token }}'
                        })
                        .done(function (data) {
                            UIkit.notification({message: 'New water fountain added. Lat: ' + lat + ', Lng: ' + lng + '!'});
                            marker.id = data.id;
                            infowindow.close();
                        })
                        .fail(function () {
                            UIkit.notification({message: 'Failed adding new water fountain.', status: 'danger'});
                        });
                }
            }

            function deleteWaterFountain() {
                id = marker.id;
                if (id == null) {
                    marker.setMap(null);
                    return;
                }
                $.post("{% url "carav:delete_water_fountain" %}",
                    {
                        id: id,
                        csrfmiddlewaretoken: '{{ csrf_token }}'
                    })
                    .done(function () {
                        UIkit.notification({message: 'Water fountain deleted!'});
                        marker.setMap(null);
                    })
                    .fail(function () {
                        UIkit.notification({message: 'Failed deleting water fountain.', status: 'danger'});
                    });
            }

        </script>
        <script async defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCv9ceYkFkzo-P8MmRIvJxxeU-mcfEBdOI&callback=initMap"></script>

    {% endspaceless %}

{% endblock html_body %}

homepage/templates/base.html
{% spaceless %}
    {% load static %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>{% block title %}Lazy Developer{% endblock title %} - Lazy Developer</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.8/css/uikit.css"/>
        <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Noto+Sans">
        <link rel="icon" type="image/png" href="{% static 'favicon-32x32.png' %}" sizes="32x32"/>
        <link rel="icon" type="image/png" href="{% static 'favicon-16x16.png' %}" sizes="16x16"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.8/js/uikit.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.8/js/uikit-icons.js"></script>
        {% block head %}{% endblock head %}
    </head>
    <body>
    {% block html_body %}{% endblock html_body %}
    </body>
    </html>
{% endspaceless %}

homepage/templates/base_formatted.html
{% extends "base.html" %}

{% load static %}

{% block html_body %}

    {% spaceless %}

        <div class="content">

            <div class="uk-background-cover uk-flex background-grey min-height-300">
                <div class="uk-width-auto uk-text-center uk-margin-auto uk-margin-auto-vertical">
                    <h1 class="uk-heading-primary uk-text-uppercase uk-width-auto uk-text-center uk-margin-auto uk-margin-auto-vertical">{% block title %}{% endblock title %}</h1>
                </div>
            </div>

            <div class="uk-container uk-container-small uk-margin-large">
                <div class="uk-grid-match uk-flex-column" data-uk-grid>
                    <div>
                        {% block content %}{% endblock content %}
                    </div>
                </div>
            </div>

        </div>

        {% include "footer.html" %}

    {% endspaceless %}

{% endblock html_body %}

templates/base.html
{% load static %}
{% spaceless %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.28/css/uikit.css"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="icon" type="image/png" href="{% static 'favicon-32x32.png' %}" sizes="32x32"/>
    <link rel="icon" type="image/png" href="{% static 'favicon-16x16.png' %}" sizes="16x16"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.28/js/uikit.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.28/js/uikit-icons.js"></script>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>
{% endspaceless %}